config/routes.rb
Rails.application.routes.draw do
  resources :streams, only: [:index, :new, :create, :destroy]   
   root "streams#index"  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stream.rb
class Stream < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
    validates :name, presence: true # Make sure the owner's name is present.   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  def index   
    @streams = Stream.all   
 end   
    
 def new   
    @stream = Stream.new   
 end   
    
 def create   
    @stream = Stream.new(stream_params)   
       
    # if @stream.save   
      #  redirect_to steams_path, notice: "Successfully uploaded."   
    # else   
       render "new"   
    # end   
       
 end   
    
 def destroy   
    @stream = Stream.find(params[:id])   
    @stream.destroy   
    redirect_to streams_path, notice:  "Successfully deleted."   
 end   
    
 private   
    def stream_params   
    params.require(:stream).permit(:name, :attachment)   
 end   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>File Uploading</title>   
      <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>   
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>   

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/streams/create.html.erb
<h1>Streams#create</h1>
<p>Find me in app/views/streams/create.html.erb</p>

app/views/streams/destroy.html.erb
<h1>Streams#destroy</h1>
<p>Find me in app/views/streams/destroy.html.erb</p>

app/views/streams/index.html.erb
<div class="container">   
<% if !flash[:notice].blank? %>   
   <div>   
      <%= flash[:notice] %>   
   </div>   
<% end %>   
  
<br>   
  
<%= link_to "New Stream", new_stream_path %>   
<br>   
<br>   
  
<table border="3">   
   <thead>   
      <tr>   
         <th>Candidate Name</th>   
         <th>Download Link</th>   
         <th>Action</th>   
      </tr>   
   </thead>   
      
   <tbody>   
      <% @streams.each do |stream| %>   
            
         <tr>   
            <td><%= stream.name %></td>   
            <td><%= link_to "Download", stream.attachment_url %></td>   
            <td><%= link_to "Delete",  stream, method: :delete, confirm: "Are you sure you want to delete #{stream.name}?" %></td>   
         </tr>   
            
      <% end %>   
   </tbody>   
      
</table>   
</div>  

app/views/streams/new.html.erb
<div class="container">   
<% if !@stream.errors.empty? %>   
   <div>   
         
      <ul>   
         <% @stream.errors.full_messages.each do |msg| %>   
            <li><%= msg %></li>   
         <% end %>   
         <% end %>
<div class="container">   
<% if !@stream.errors.empty? %>   
   <div>   
         
      <ul>   
         <% @stream.errors.full_messages.each do |msg| %>   
            <li><%= msg %></li>   
         <% end %>      </ul>   
         
   </div>   
<% end %>   
  
<div>   
   <%= form_for @stream, html: { multipart: true } do |f| %>   
      <%= f.label :name %>   
      <%= f.text_field :name %>   
      <br><br>   
      <%= f.label :attachment %>   
      <%= f.file_field :attachment %>   
      <br>   
      <%= f.submit "Save" %>   
   <% end %>   
</div>   
</div>  